#!/usr/bin/python3

import argparse

from libqoqa import qoqa
from colorama import init, Fore

init(autoreset=True)


def main():
    """
    Main Entry point for qoqa
    """
    parser = argparse.ArgumentParser(description="Qoqa is an application to"
                                     " create a new django project and to"
                                     " build the django project")
    parser.add_argument('action', nargs=2, help='use new, build or release')
    args = parser.parse_args()
    if args.action:
        if args.action[0] == 'new':
            qoqa.create(args.action[1])
        elif args.action[0] == 'build':
            qoqa.new_build(args.action[1])
        elif args.action[0] == 'release':
            qoqa.release(args.action[1])
        else:
            print(Fore.RED + '[qoqa] Unknown argument use either new, build or release')
            exit()


if __name__ == '__main__':
    main()
