#!/usr/bin/python3

import argparse

from libqoqa import qoqa


def main():
    """
    Main Entry point for qoqa
    """
    parser = argparse.ArgumentParser(description="Qoqa is an application to"
                                     "create a new django project and to"
                                     "build the django project")
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--new', help='Create new django project')
    group.add_argument('--build', help='setup project for next release')
    group.add_argument('--release', help='build .deb file of project')
    args = parser.parse_args()

    if args.new:
        qoqa.new(args.new)
    elif args.build:
        qoqa.new_build(args.build)
    elif args.release:
        qoqa.release(args.release)


if __name__ == '__main__':
    main()
