#!/usr/bin/python3

import argparse

from libqoqa import qoqa
from colorama import init, Fore

init(autoreset=True)


def main():
    """
    Main Entry point for qoqa
    """
    parser = argparse.ArgumentParser(description="Qoqa is an application to"
                                     " create a new django project and to"
                                     " build the django project")
    parser.add_argument('action', nargs=2, help='new, build, release, env')
    parser.add_argument('--django', help='specify django version')
    args = parser.parse_args()
    if args.action:
        if args.action[0] == 'new':
            if args.django:
                qoqa.create(args.action[1], django=args.django)
            else:
                print(Fore.RED + '[qoqa] specify a django version')
        elif args.action[0] == 'build':
            qoqa.new_build(args.action[1])
        elif args.action[0] == 'release':
            qoqa.release(args.action[1])
        elif args.action[0] == 'env':
            if args.django:
                qoqa.env(args.action[1], args.django)
            else:
                print(Fore.RED + '[qoqa] specify a django version')
        else:
            print(Fore.RED + '[qoqa] Unknown argument use either new,'
                  'build or release, env')
            exit()


if __name__ == '__main__':
    main()
